# Generated by Django 3.2.7 on 2021-09-19 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0003_aboutpage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutpage',
            options={'verbose_name_plural': 'About page infó'},
        ),
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name_plural': 'Home page infó'},
        ),
        migrations.AlterModelOptions(
            name='pageinfo',
            options={'verbose_name_plural': 'Oldal infó'},
        ),
    ]
